/* Content for ai-news.html.

   This file is normally auto-generated by scripts/fetch_and_rewrite_news.py,
   run on a schedule by .github/workflows/ai-news-autoupdate.yml — see
   news/ai-news-setup.md for the one-time setup (adding an ANTHROPIC_API_KEY
   secret) that turns the automation on.

   Until that's set up, this file holds a hand-written seed snapshot so the
   page has real content from day one. Once the automation runs successfully
   for the first time, it overwrites this file — there's nothing else to do. */
window.AITS_NEWS = {
  "en": {
    "snapshotDate": "August 31, 2026",
    "items": [
      { "date": "Aug 28, 2026", "title": "Claude Code adds model-switch hooks, live Remote Control streaming, and a spend limit bar", "summary": "Version 2.1.251 introduced PreModelSwitch/PostModelSwitch hook events, live streaming of subagent tool calls to Remote Control clients, and a spend limit bar in /usage.", "source": "Releasebot — Claude Code changelog", "url": "https://releasebot.io/updates/anthropic/claude-code" },
      { "date": "Aug 26, 2026", "title": "Salesforce and Anthropic announce \"Claudeforce\"", "summary": "An expanded strategic partnership bringing Claude's intelligence directly into Salesforce's CRM products.", "source": "Salesforce Newsroom", "url": "https://www.salesforce.com/news/press-releases/2026/08/26/salesforce-and-anthropic-announce-claudeforce/" },
      { "date": "Aug 16, 2026", "title": "Major outage affected Claude.ai, Claude Code, and Claude Cowork", "summary": "Anthropic confirmed an incident causing sign-in problems, failed loads, and incomplete requests across multiple Claude products.", "source": "BleepingComputer", "url": "https://www.bleepingcomputer.com/news/artificial-intelligence/anthropic-confirms-claude-is-down-in-major-outage-affecting-multiple-services/" },
      { "date": "Aug 14, 2026", "title": "Claude Code's auto mode turned on by default", "summary": "Pro, Max, and Team accounts now default to auto mode, letting Claude Code carry out more of a task before asking for a check-in.", "source": "TechCrunch", "url": "https://techcrunch.com/2026/08/09/anthropic-is-turning-claude-codes-auto-mode-on-by-default/" },
      { "date": "Aug 11, 2026", "title": "Anthropic to watermark all Claude outputs worldwide", "summary": "Machine-readable watermarking, added to meet EU AI Act transparency rules, now applies globally to Claude's generated text and files.", "source": "Euronews", "url": "https://www.euronews.com/next/2026/08/11/eu-compliance-delivered-globally-anthropic-to-watermark-claudes-output-worldwide" },
      { "date": "Aug 2026", "title": "Claude Sonnet 5 introduced as the new default model", "summary": "Ships with a native 1M-token context window, alongside continued performance and startup-time improvements across Claude Code.", "source": "Releasebot — Claude changelog", "url": "https://releasebot.io/updates/anthropic/claude" },
      { "date": "Aug 2026", "title": "Claude for K-12 Academy expanded with free AI-fluency content", "summary": "New courses, guides, and classroom workflows aimed at teachers, coaches, and district teams adopting AI in schools.", "source": "Anthropic Newsroom", "url": "https://www.anthropic.com/news" }
    ]
  },
  "pt": {
    "snapshotDate": "31 de agosto de 2026",
    "items": [
      { "date": "28 de ago. de 2026", "title": "Claude Code adiciona hooks de troca de modelo, streaming ao vivo no Remote Control e uma barra de limite de gastos", "summary": "A versão 2.1.251 trouxe os eventos de hook PreModelSwitch/PostModelSwitch, streaming ao vivo das chamadas de ferramentas de subagentes para clientes do Remote Control, e uma barra de limite de gastos no /usage.", "source": "Releasebot — changelog do Claude Code", "url": "https://releasebot.io/updates/anthropic/claude-code" },
      { "date": "26 de ago. de 2026", "title": "Salesforce e Anthropic anunciam a \"Claudeforce\"", "summary": "Uma parceria estratégica ampliada que leva a inteligência do Claude diretamente para os produtos de CRM da Salesforce.", "source": "Sala de imprensa da Salesforce", "url": "https://www.salesforce.com/news/press-releases/2026/08/26/salesforce-and-anthropic-announce-claudeforce/" },
      { "date": "16 de ago. de 2026", "title": "Grande instabilidade afetou o Claude.ai, o Claude Code e o Claude Cowork", "summary": "A Anthropic confirmou um incidente que causou problemas de login, falhas de carregamento e pedidos incompletos em vários produtos do Claude.", "source": "BleepingComputer", "url": "https://www.bleepingcomputer.com/news/artificial-intelligence/anthropic-confirms-claude-is-down-in-major-outage-affecting-multiple-services/" },
      { "date": "14 de ago. de 2026", "title": "O modo automático do Claude Code passou a vir ativado por padrão", "summary": "Contas Pro, Max e Team agora usam o modo automático por padrão, permitindo que o Claude Code realize mais partes de uma tarefa antes de pedir uma checagem.", "source": "TechCrunch", "url": "https://techcrunch.com/2026/08/09/anthropic-is-turning-claude-codes-auto-mode-on-by-default/" },
      { "date": "11 de ago. de 2026", "title": "Anthropic vai marcar com marca d'água todas as saídas do Claude no mundo todo", "summary": "Marcação legível por máquina, adicionada para cumprir as regras de transparência do AI Act da UE, agora se aplica globalmente aos textos e arquivos gerados pelo Claude.", "source": "Euronews", "url": "https://www.euronews.com/next/2026/08/11/eu-compliance-delivered-globally-anthropic-to-watermark-claudes-output-worldwide" },
      { "date": "ago. de 2026", "title": "Claude Sonnet 5 é apresentado como o novo modelo padrão", "summary": "Vem com uma janela de contexto nativa de 1 milhão de tokens, além de melhorias contínuas de desempenho e tempo de inicialização no Claude Code.", "source": "Releasebot — changelog do Claude", "url": "https://releasebot.io/updates/anthropic/claude" },
      { "date": "ago. de 2026", "title": "Claude for K-12 Academy é ampliada com conteúdo gratuito de fluência em IA", "summary": "Novos cursos, guias e fluxos de trabalho para sala de aula voltados a professores, coordenadores e equipes de redes escolares que estão adotando IA.", "source": "Sala de imprensa da Anthropic", "url": "https://www.anthropic.com/news" }
    ]
  },
  "es": {
    "snapshotDate": "31 de agosto de 2026",
    "items": [
      { "date": "28 ago. 2026", "title": "Claude Code agrega hooks de cambio de modelo, streaming en vivo en Remote Control y una barra de límite de gasto", "summary": "La versión 2.1.251 introdujo los eventos de hook PreModelSwitch/PostModelSwitch, streaming en vivo de las llamadas a herramientas de subagentes hacia clientes de Remote Control, y una barra de límite de gasto en /usage.", "source": "Releasebot — changelog de Claude Code", "url": "https://releasebot.io/updates/anthropic/claude-code" },
      { "date": "26 ago. 2026", "title": "Salesforce y Anthropic anuncian \"Claudeforce\"", "summary": "Una alianza estratégica ampliada que lleva la inteligencia de Claude directamente a los productos de CRM de Salesforce.", "source": "Sala de prensa de Salesforce", "url": "https://www.salesforce.com/news/press-releases/2026/08/26/salesforce-and-anthropic-announce-claudeforce/" },
      { "date": "16 ago. 2026", "title": "Una gran interrupción afectó a Claude.ai, Claude Code y Claude Cowork", "summary": "Anthropic confirmó un incidente que causó problemas para iniciar sesión, fallas de carga y solicitudes incompletas en varios productos de Claude.", "source": "BleepingComputer", "url": "https://www.bleepingcomputer.com/news/artificial-intelligence/anthropic-confirms-claude-is-down-in-major-outage-affecting-multiple-services/" },
      { "date": "14 ago. 2026", "title": "El modo automático de Claude Code ahora viene activado por defecto", "summary": "Las cuentas Pro, Max y Team ahora usan el modo automático por defecto, permitiendo que Claude Code realice más partes de una tarea antes de pedir una revisión.", "source": "TechCrunch", "url": "https://techcrunch.com/2026/08/09/anthropic-is-turning-claude-codes-auto-mode-on-by-default/" },
      { "date": "11 ago. 2026", "title": "Anthropic marcará con marca de agua todas las salidas de Claude en todo el mundo", "summary": "El marcado legible por máquina, agregado para cumplir las reglas de transparencia de la Ley de IA de la UE, ahora se aplica globalmente a los textos y archivos generados por Claude.", "source": "Euronews", "url": "https://www.euronews.com/next/2026/08/11/eu-compliance-delivered-globally-anthropic-to-watermark-claudes-output-worldwide" },
      { "date": "ago. 2026", "title": "Claude Sonnet 5 se presenta como el nuevo modelo predeterminado", "summary": "Viene con una ventana de contexto nativa de 1 millón de tokens, junto con mejoras continuas de rendimiento y tiempo de inicio en Claude Code.", "source": "Releasebot — changelog de Claude", "url": "https://releasebot.io/updates/anthropic/claude" },
      { "date": "ago. 2026", "title": "Claude for K-12 Academy se amplía con contenido gratuito de alfabetización en IA", "summary": "Nuevos cursos, guías y flujos de trabajo de aula dirigidos a docentes, coordinadores y equipos de distritos escolares que están adoptando IA.", "source": "Sala de prensa de Anthropic", "url": "https://www.anthropic.com/news" }
    ]
  }
};
