/* Auto-generated by scripts/fetch_and_rewrite_news.py — do not hand-edit.
   Regenerated on a schedule by .github/workflows/ai-news-autoupdate.yml.
   See news/ai-news-setup.md for how the pipeline is configured. */
window.AITS_NEWS = {
  "en": {
    "snapshotDate": "September 1, 2026",
    "items": [
      {
        "date": "Aug 29, 2026",
        "title": "Sony Music, Warner sue Anthropic, alleging a ‘brazen campaign’ of intellectual property theft",
        "summary": "Sony Music and Warner Bros. filed a lawsuit against Anthropic, claiming the company illegally used their copyrighted music catalogs to train AI models without permission.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/29/sony-music-warner-sue-anthropic-alleging-a-brazen-campaign-of-intellectual-property-theft/"
      },
      {
        "date": "Aug 28, 2026",
        "title": "An Anthropic researcher just gave us a peek at self-improving AI",
        "summary": "An Anthropic research team demonstrated that an automated AI system could identify and correct its own misaligned behaviors across multiple benchmarks without hurting its overall performance.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/28/an-anthropic-researcher-just-gave-us-a-peek-at-self-improving-ai/"
      },
      {
        "date": "Aug 28, 2026",
        "title": "Anthropic gets its first court win over the Pentagon’s supply-chain risk label",
        "summary": "A federal court ruled that the Trump administration's classification of Anthropic as a supply-chain risk was unlawful, marking a victory in the company's dispute with the Pentagon.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/28/anthropic-gets-its-first-court-win-over-the-pentagons-supply-chain-risk-label/"
      },
      {
        "date": "Aug 19, 2026",
        "title": "VentureBeat names Rob Strechay as its first Lead Analyst, expanding its enterprise AI research push",
        "summary": "VentureBeat hired Rob Strechay as its first Lead Analyst to provide technical research for enterprise technology decision-makers evaluating AI infrastructure and deployment strategies.",
        "source": "AI | VentureBeat",
        "url": "https://venturebeat.com/ai/venturebeat-names-rob-strechay-as-its-first-lead-analyst-expanding-its-enterprise-ai-research-push"
      },
      {
        "date": "Jan 22, 2026",
        "title": "Railway secures $100 million to challenge AWS with AI-native cloud infrastructure",
        "summary": "Railway, a cloud platform built to match the speed of AI coding tools, raised $100 million in Series B funding after reaching over 10 million monthly deployments by focusing on fast infrastructure and lower costs than traditional cloud providers.",
        "source": "AI | VentureBeat",
        "url": "https://venturebeat.com/infrastructure/railway-secures-usd100-million-to-challenge-aws-with-ai-native-cloud"
      },
      {
        "date": "Jan 19, 2026",
        "title": "Claude Code costs up to $200 a month. Goose does the same thing for free.",
        "summary": "Goose, a free open-source AI coding agent from Block, offers similar capabilities to Claude Code without subscription fees by running entirely on a user's local computer with offline functionality.",
        "source": "AI | VentureBeat",
        "url": "https://venturebeat.com/infrastructure/claude-code-costs-up-to-usd200-a-month-goose-does-the-same-thing-for-free"
      },
      {
        "date": "Sep 1, 2026",
        "title": "Apple shares ‘shocking evidence’ against former employee accused of stealing company data for OpenAI",
        "summary": "Apple presented evidence that a former employee who is accused of stealing confidential data to give to OpenAI destroyed evidence after learning he was under investigation.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/31/apple-shares-shocking-evidence-against-former-employee-accused-of-stealing-company-data-for-openai/"
      }
    ]
  },
  "pt": {
    "snapshotDate": "1 de set. de 2026",
    "items": [
      {
        "date": "29 de ago. de 2026",
        "title": "Sony Music, Warner sue Anthropic, alleging a ‘brazen campaign’ of intellectual property theft",
        "summary": "Sony Music e Warner Bros. entraram com uma ação judicial contra a Anthropic, alegando que a empresa usou ilegalmente seus catálogos de música protegidos por direitos autorais para treinar modelos de IA sem permissão.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/29/sony-music-warner-sue-anthropic-alleging-a-brazen-campaign-of-intellectual-property-theft/"
      },
      {
        "date": "28 de ago. de 2026",
        "title": "An Anthropic researcher just gave us a peek at self-improving AI",
        "summary": "Um time de pesquisa da Anthropic demonstrou que um sistema de IA automatizado conseguiu identificar e corrigir seus próprios comportamentos desalinhados em vários benchmarks sem prejudicar seu desempenho geral.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/28/an-anthropic-researcher-just-gave-us-a-peek-at-self-improving-ai/"
      },
      {
        "date": "28 de ago. de 2026",
        "title": "Anthropic gets its first court win over the Pentagon’s supply-chain risk label",
        "summary": "Uma corte federal determinou que a classificação da Anthropic como risco da cadeia de suprimentos pela administração Trump era ilegal, marcando uma vitória na disputa da empresa com o Pentágono.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/28/anthropic-gets-its-first-court-win-over-the-pentagons-supply-chain-risk-label/"
      },
      {
        "date": "19 de ago. de 2026",
        "title": "VentureBeat names Rob Strechay as its first Lead Analyst, expanding its enterprise AI research push",
        "summary": "VentureBeat contratou Rob Strechay como seu primeiro Lead Analyst para fornecer pesquisa técnica aos tomadores de decisão de tecnologia empresarial que avaliam estratégias de infraestrutura de IA e implantação.",
        "source": "AI | VentureBeat",
        "url": "https://venturebeat.com/ai/venturebeat-names-rob-strechay-as-its-first-lead-analyst-expanding-its-enterprise-ai-research-push"
      },
      {
        "date": "22 de jan. de 2026",
        "title": "Railway secures $100 million to challenge AWS with AI-native cloud infrastructure",
        "summary": "Railway, uma plataforma de cloud construída para acompanhar a velocidade das ferramentas de codificação com IA, arrecadou $100 milhões em financiamento da Série B após atingir mais de 10 milhões de implantações mensais, focando em infraestrutura rápida e custos menores que os provedores de cloud tradicionais.",
        "source": "AI | VentureBeat",
        "url": "https://venturebeat.com/infrastructure/railway-secures-usd100-million-to-challenge-aws-with-ai-native-cloud"
      },
      {
        "date": "19 de jan. de 2026",
        "title": "Claude Code costs up to $200 a month. Goose does the same thing for free.",
        "summary": "Goose, um agente de codificação com IA de código aberto gratuito da Block, oferece recursos similares ao Claude Code sem taxas de assinatura ao funcionar inteiramente no computador local do usuário com funcionalidade offline.",
        "source": "AI | VentureBeat",
        "url": "https://venturebeat.com/infrastructure/claude-code-costs-up-to-usd200-a-month-goose-does-the-same-thing-for-free"
      },
      {
        "date": "1 de set. de 2026",
        "title": "Apple shares ‘shocking evidence’ against former employee accused of stealing company data for OpenAI",
        "summary": "Apple apresentou evidências de que um ex-funcionário acusado de roubar dados confidenciais para entregar ao OpenAI destruiu evidências após saber que estava sendo investigado.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/31/apple-shares-shocking-evidence-against-former-employee-accused-of-stealing-company-data-for-openai/"
      }
    ]
  },
  "es": {
    "snapshotDate": "1 de sep. de 2026",
    "items": [
      {
        "date": "29 de ago. de 2026",
        "title": "Sony Music, Warner sue Anthropic, alleging a ‘brazen campaign’ of intellectual property theft",
        "summary": "Sony Music y Warner Bros. presentaron una demanda contra Anthropic, alegando que la empresa utilizó ilegalmente sus catálogos de música protegidos por derechos de autor para entrenar modelos de IA sin permiso.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/29/sony-music-warner-sue-anthropic-alleging-a-brazen-campaign-of-intellectual-property-theft/"
      },
      {
        "date": "28 de ago. de 2026",
        "title": "An Anthropic researcher just gave us a peek at self-improving AI",
        "summary": "Un equipo de investigación de Anthropic demostró que un sistema de IA automatizado podría identificar y corregir sus propios comportamientos desalineados en múltiples puntos de referencia sin dañar su rendimiento general.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/28/an-anthropic-researcher-just-gave-us-a-peek-at-self-improving-ai/"
      },
      {
        "date": "28 de ago. de 2026",
        "title": "Anthropic gets its first court win over the Pentagon’s supply-chain risk label",
        "summary": "Un tribunal federal determinó que la clasificación de Anthropic como riesgo de la cadena de suministros por parte de la administración Trump fue ilegal, marcando una victoria en la disputa de la empresa con el Pentágono.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/28/anthropic-gets-its-first-court-win-over-the-pentagons-supply-chain-risk-label/"
      },
      {
        "date": "19 de ago. de 2026",
        "title": "VentureBeat names Rob Strechay as its first Lead Analyst, expanding its enterprise AI research push",
        "summary": "VentureBeat contrató a Rob Strechay como su primer Lead Analyst para proporcionar investigación técnica a los tomadores de decisiones de tecnología empresarial que evalúan estrategias de infraestructura de IA e implementación.",
        "source": "AI | VentureBeat",
        "url": "https://venturebeat.com/ai/venturebeat-names-rob-strechay-as-its-first-lead-analyst-expanding-its-enterprise-ai-research-push"
      },
      {
        "date": "22 de ene. de 2026",
        "title": "Railway secures $100 million to challenge AWS with AI-native cloud infrastructure",
        "summary": "Railway, una plataforma en la nube construida para igualar la velocidad de las herramientas de codificación con IA, recaudó $100 millones en financiamiento de la Serie B después de alcanzar más de 10 millones de implementaciones mensuales, enfocándose en infraestructura rápida y costos más bajos que los proveedores de nube tradicionales.",
        "source": "AI | VentureBeat",
        "url": "https://venturebeat.com/infrastructure/railway-secures-usd100-million-to-challenge-aws-with-ai-native-cloud"
      },
      {
        "date": "19 de ene. de 2026",
        "title": "Claude Code costs up to $200 a month. Goose does the same thing for free.",
        "summary": "Goose, un agente de codificación con IA de código abierto gratuito de Block, ofrece capacidades similares a Claude Code sin tarifas de suscripción al ejecutarse completamente en la computadora local del usuario con funcionalidad sin conexión.",
        "source": "AI | VentureBeat",
        "url": "https://venturebeat.com/infrastructure/claude-code-costs-up-to-usd200-a-month-goose-does-the-same-thing-for-free"
      },
      {
        "date": "1 de sep. de 2026",
        "title": "Apple shares ‘shocking evidence’ against former employee accused of stealing company data for OpenAI",
        "summary": "Apple presentó evidencia de que un ex-empleado acusado de robar datos confidenciales para entregar a OpenAI destruyó evidencia después de enterarse de que estaba siendo investigado.",
        "source": "AI News & Artificial Intelligence | TechCrunch",
        "url": "https://techcrunch.com/2026/08/31/apple-shares-shocking-evidence-against-former-employee-accused-of-stealing-company-data-for-openai/"
      }
    ]
  }
};
